I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 384, in script
    Wesley "You'll pay for that!"
Exception: Sayer 'Wesley' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 384, in script
    Wesley "You'll pay for that!"
  File "R:\Tools\renpy-7.1.0-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "R:\Tools\renpy-7.1.0-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Wesley' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.0.882
CS Bounciness Vol. 3 1.0
Tue Feb 25 22:17:22 2020
